// 紧凑地区搜索关键词映射（小写英文、中文及别名）
const REGION_SEARCH_MAP: Record<string, string> = {
  '🇭🇰': 'hong kong,香港,hk,hongkong',
  '🇨🇳': 'china,中国,cn,中华人民共和国,prc',
  '🇺🇸': 'united states,美国,us,usa,america,美利坚',
  '🇯🇵': 'japan,日本,jp',
  '🇰🇷': 'south korea,韩国,kr,korea,南韩',
  '🇸🇬': 'singapore,新加坡,sg',
  '🇹🇼': 'taiwan,台湾,tw,台灣',
  '🇬🇧': 'united kingdom,英国,gb,uk,britain,英國',
  '🇩🇪': 'germany,德国,de,deutschland,德國',
  '🇫🇷': 'france,法国,fr,法國',
  '🇨🇦': 'canada,加拿大,ca',
  '🇦🇺': 'australia,澳大利亚,au,澳洲',
  '🇷🇺': 'russia,俄罗斯,ru,俄國',
  '🇮🇳': 'india,印度,in',
  '🇧🇷': 'brazil,巴西,br',
  '🇳🇱': 'netherlands,荷兰,nl,holland,荷蘭',
  '🇮🇹': 'italy,意大利,it',
  '🇪🇸': 'spain,西班牙,es',
  '🇸🇪': 'sweden,瑞典,se',
  '🇳🇴': 'norway,挪威,no',
  '🇫🇮': 'finland,芬兰,fi,芬蘭',
  '🇨🇭': 'switzerland,瑞士,ch',
  '🇦🇹': 'austria,奥地利,at,奧地利',
  '🇧🇪': 'belgium,比利时,be,比利時',
  '🇵🇹': 'portugal,葡萄牙,pt',
  '🇬🇷': 'greece,希腊,gr,希臘',
  '🇹🇷': 'turkey,土耳其,tr',
  '🇵🇱': 'poland,波兰,pl,波蘭',
  '🇨🇿': 'czech republic,捷克,cz,czech',
  '🇭🇺': 'hungary,匈牙利,hu',
  '🇷🇴': 'romania,罗马尼亚,ro,羅馬尼亞',
  '🇧🇬': 'bulgaria,保加利亚,bg,保加利亞',
  '🇭🇷': 'croatia,克罗地亚,hr,克羅地亞',
  '🇸🇮': 'slovenia,斯洛文尼亚,si,斯洛文尼亞',
  '🇸🇰': 'slovakia,斯洛伐克,sk',
  '🇱🇻': 'latvia,拉脱维亚,lv,拉脫維亞',
  '🇱🇹': 'lithuania,立陶宛,lt',
  '🇪🇪': 'estonia,爱沙尼亚,ee,愛沙尼亞',
  '🇲🇽': 'mexico,墨西哥,mx',
  '🇦🇷': 'argentina,阿根廷,ar',
  '🇨🇱': 'chile,智利,cl',
  '🇨🇴': 'colombia,哥伦比亚,co,哥倫比亞',
  '🇵🇪': 'peru,秘鲁,pe,秘魯',
  '🇻🇪': 'venezuela,委内瑞拉,ve,委內瑞拉',
  '🇺🇾': 'uruguay,乌拉圭,uy,烏拉圭',
  '🇪🇨': 'ecuador,厄瓜多尔,ec,厄瓜多爾',
  '🇧🇴': 'bolivia,玻利维亚,bo,玻利維亞',
  '🇵🇾': 'paraguay,巴拉圭,py',
  '🇬🇾': 'guyana,圭亚那,gy,圭亞那',
  '🇸🇷': 'suriname,苏里南,sr,蘇里南',
  '🇫🇰': 'falkland islands,福克兰群岛,fk,falkland,福克兰,福克蘭',
  '🇬🇫': 'french guiana,法属圭亚那,gf,法屬圭亞那',
  '🇵🇦': 'panama,巴拿马,pa,巴拿馬',
  '🇨🇷': 'costa rica,哥斯达黎加,cr,哥斯達黎加',
  '🇳🇮': 'nicaragua,尼加拉瓜,ni',
  '🇭🇳': 'honduras,洪都拉斯,hn',
  '🇬🇹': 'guatemala,危地马拉,gt,危地馬拉',
  '🇧🇿': 'belize,伯利兹,bz,伯利茲',
  '🇸🇻': 'el salvador,萨尔瓦多,sv,薩爾瓦多',
  '🇯🇲': 'jamaica,牙买加,jm,牙買加',
  '🇨🇺': 'cuba,古巴,cu',
  '🇩🇴': 'dominican republic,多明尼加,do,dominican',
  '🇭🇹': 'haiti,海地,ht',
  '🇧🇸': 'bahamas,巴哈马,bs,巴哈馬',
  '🇧🇧': 'barbados,巴巴多斯,bb',
  '🇹🇹': 'trinidad and tobago,特立尼达和多巴哥,tt,trinidad,特立尼达,特立尼達',
  '🇵🇭': 'philippines,菲律宾,ph,菲律賓',
  '🇹🇭': 'thailand,泰国,th,泰國',
  '🇻🇳': 'vietnam,越南,vn',
  '🇲🇾': 'malaysia,马来西亚,my,馬來西亞',
  '🇮🇩': 'indonesia,印度尼西亚,id,印尼',
  '🇱🇦': 'laos,老挝,la,老撾',
  '🇰🇭': 'cambodia,柬埔寨,kh',
  '🇲🇲': 'myanmar,缅甸,mm,burma,緬甸',
  '🇧🇳': 'brunei,文莱,bn,汶萊',
  '🇪🇬': 'egypt,埃及,eg',
  '🇿🇦': 'south africa,南非,za',
  '🇳🇬': 'nigeria,尼日利亚,ng,尼日利亞',
  '🇰🇪': 'kenya,肯尼亚,ke,肯亞',
  '🇪🇹': 'ethiopia,埃塞俄比亚,et,埃塞俄比亞',
  '🇬🇭': 'ghana,加纳,gh,迦納',
  '🇺🇬': 'uganda,乌干达,ug,烏干達',
  '🇹🇿': 'tanzania,坦桑尼亚,tz,坦尚尼亞',
  '🇷🇼': 'rwanda,卢旺达,rw,盧旺達',
  '🇿🇼': 'zimbabwe,津巴布韦,zw,辛巴威',
  '🇿🇲': 'zambia,赞比亚,zm,尚比亞',
  '🇧🇼': 'botswana,博茨瓦纳,bw,波札那',
  '🇳🇦': 'namibia,纳米比亚,na,納米比亞',
  '🇲🇦': 'morocco,摩洛哥,ma',
  '🇩🇿': 'algeria,阿尔及利亚,dz,阿爾及利亞',
  '🇹🇳': 'tunisia,突尼斯,tn',
  '🇱🇾': 'libya,利比亚,ly,利比亞',
  '🇸🇩': 'sudan,苏丹,sd,蘇丹',
  '🇸🇸': 'south sudan,南苏丹,ss,南蘇丹',
  '🇨🇩': 'democratic republic of congo,刚果民主共和国,cd,congo,drc,刚果,剛果',
  '🇨🇬': 'republic of congo,刚果共和国,cg,congo,刚果,剛果',
  '🇨🇫': 'central african republic,中非共和国,cf,central african,中非',
  '🇨🇲': 'cameroon,喀麦隆,cm,喀麥隆',
  '🇹🇩': 'chad,乍得,td',
  '🇳🇪': 'niger,尼日尔,ne,尼日爾',
  '🇲🇱': 'mali,马里,ml,馬利',
  '🇧🇫': 'burkina faso,布基纳法索,bf,burkina,布吉納法索',
  '🇸🇳': 'senegal,塞内加尔,sn,塞內加爾',
  '🇬🇲': 'gambia,冈比亚,gm,甘比亞',
  '🇬🇼': 'guinea-bissau,几内亚比绍,gw,幾內亞比索',
  '🇬🇳': 'guinea,几内亚,gn,幾內亞',
  '🇸🇱': 'sierra leone,塞拉利昂,sl',
  '🇱🇷': 'liberia,利比里亚,lr,賴比瑞亞',
  '🇨🇮': 'ivory coast,科特迪瓦,ci,象牙海岸',
  '🇹🇬': 'togo,多哥,tg',
  '🇧🇯': 'benin,贝宁,bj,貝寧',
};

export const isRegionMatch = (regionEmoji: string, searchTerm: string): boolean => {
  const term = searchTerm.toLowerCase().trim();
  if (!term) return true;
  if (regionEmoji === searchTerm) return true;
  const keywords = REGION_SEARCH_MAP[regionEmoji];
  if (keywords) {
    return keywords.includes(term);
  }
  return regionEmoji.toLowerCase().includes(term);
};
